# Generated by Django 3.2.11 on 2022-02-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('uid', models.CharField(max_length=200)),
                ('roomname', models.CharField(max_length=200)),
            ],
        ),
    ]
