# Generated by Django 3.2.11 on 2022-02-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommember',
            old_name='roomname',
            new_name='room_name',
        ),
    ]
